# Generated by Selenium IDE
from selenium.webdriver.common.by import By
from core.selenium.common import initialize_driver, close_drive


def test_checkdatasetuser(self):
    driver = initialize_driver()

    try:
        driver.get("http://127.0.0.1:5000/")
        driver.set_window_size(1854, 1048)
        driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
        driver.find_element(By.LINK_TEXT, "Doe, Jane").click()
        driver.find_element(By.LINK_TEXT, "Sample dataset 2").click()
    finally:
        close_drive(driver)


# Call the test function
test_checkdatasetuser()
