"""create_bot_model

Revision ID: 094bc564c1de
Revises: 001
Create Date: 2024-12-05 10:30:20.635942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094bc564c1de'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('on_download_dataset', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot')
    # ### end Alembic commands ###
