"""added_bot_service_name

Revision ID: 144829fab01f
Revises: 094bc564c1de
Create Date: 2024-12-05 11:00:10.251284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144829fab01f'
down_revision = '094bc564c1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.drop_column('service_name')

    # ### end Alembic commands ###
