"""bot_on_download_file

Revision ID: 3f3a8104c92c
Revises: 70fcac4d95ee
Create Date: 2024-12-12 13:17:22.799881

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f3a8104c92c'
down_revision = '70fcac4d95ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('on_download_file', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.drop_column('on_download_file')

    # ### end Alembic commands ###
