"""added_bot_service_url



Revision ID: f0cd18e12ccc
Revises: 144829fab01f
Create Date: 2024-12-10 09:16:38.580152

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0cd18e12ccc'
down_revision = '144829fab01f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_url', sa.String(length=1024), nullable=False))
        batch_op.drop_column('args')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('args', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False)
        )
        batch_op.drop_column('service_url')

    # ### end Alembic commands ###
