name: Create and publish a Docker image

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
          
      - name: Build and publish Docker Image to GitHub Container Registry
        uses: TCPShield/gp-docker-action@65486288374aeae8705fc543405dc4d23de6060b
        with:
          # Github username to push Docker image from
          github-username: ${{ github.actor }}
          # GitHub token to push Docker image to GitHub Container Registry
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Docker Image tag
          image-tag: ${{ github.event.release.tag_name }}
          # Dockerfile name
          dockerfile: docker/images/Dockerfile.prod
          # Any additional docker build arguments as a string
          custom-args: VERSION_TAG=${{ github.event.release.tag_name }}
          
