name: Create and publish a Docker image

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to GHCR
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: docker build --build-arg VERSION_TAG=${{ github.event.release.tag_name }} -t espeto-hub/uvlhub:${{ github.event.release.tag_name }} -f docker/images/Dockerfile.prod .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Push Docker image to Docker Hub
        run: docker push espeto-hub/uvlhub:${{ github.event.release.tag_name }}

      - name: Tag and push latest
        run: |
          docker tag espeto-hub/uvlhub:${{ github.event.release.tag_name }} espeto-hub/uvlhub:latest
          docker push espeto-hub/uvlhub:latest
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
