name: Run Selenium tests

on:
  push:

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Setup local Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Prepare environment
      run: |
        echo "webhook" > .moduleignore
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e ./
        
    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@v2

    - name: Run migrations
      env:
        FLASK_ENV: testing
        DOMAIN: localhost:5000
        MARIADB_HOSTNAME: localhost
        MARIADB_PORT: 3306
        MARIADB_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      run: flask db upgrade

    - name: Run seeder
      env:
        FLASK_ENV: development
        DOMAIN: localhost:5000
        MARIADB_HOSTNAME: localhost
        MARIADB_PORT: 3306
        MARIADB_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      run: rosemary db:seed

    - name: Run system
      env:
        FLASK_ENV: testing
        DOMAIN: localhost:5000
        MARIADB_HOSTNAME: localhost
        MARIADB_PORT: 3306
        MARIADB_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
      uses: JarvusInnovations/background-action@v1
      with:
        run: flask run --host=0.0.0.0 --debug &
        wait-on: 'http://0.0.0.0:5000'

    - name: Waiting for system to start
      run: sleep 10
        
    - name: Run tests
      env:
        FLASK_ENV: development
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
        DISPLAY: 99
        HEADLESS: true
      run: |
        rosemary selenium
