name: Run Selenium tests

on:
  push:

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        cat <<EOF > .env
        FLASK_APP_NAME="UVLHUB.IO(dev)"
        FLASK_ENV=development
        DOMAIN=localhost
        MARIADB_HOSTNAME=db
        MARIADB_PORT=3306
        MARIADB_DATABASE=uvlhubdb
        MARIADB_TEST_DATABASE=uvlhubdb_test
        MARIADB_USER=uvlhubdb_user
        MARIADB_PASSWORD=uvlhubdb_password
        MARIADB_ROOT_PASSWORD=uvlhubdb_root_password
        WORKING_DIR=/app/
        EOF

    - name: Start containers
      run: docker compose -f docker/docker-compose.dev.yml up -d

    - name: Delete rosemary.egg-info
      run: rm -rf rosemary.egg-info

    - name: Setup local Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Prepare environment
      run: |
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e ./
        
    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@v2

    - name: Check running containers
      run: docker ps

    - name: Run Tests
      env:
        FLASK_ENV: testing
        MARIADB_HOSTNAME: 127.0.0.1
        MARIADB_PORT: 3306
        MARIADB_TEST_DATABASE: uvlhubdb_test
        MARIADB_USER: uvlhub_user
        MARIADB_PASSWORD: uvlhub_password
        DISPLAY: 99
        HEADLESS: true
      run: |
        rosemary selenium
