name: Run Selenium tests

on:
  push:
  pull_request:

jobs:
  selenium:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      FLASK_ENV: development
      DOMAIN: localhost:5000
      MARIADB_HOSTNAME: localhost
      MARIADB_PORT: 3306
      MARIADB_DATABASE: uvlhubdb_test
      MARIADB_USER: uvlhub_user
      MARIADB_PASSWORD: uvlhub_password
      WORKING_DIR: ""
      
    steps:
    - uses: actions/checkout@v4

    - name: Setup local Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Prepare environment
      run: |
        echo "webhook" > .moduleignore
        sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e ./
        
    - name: Setup Chromedriver
      uses: nanasess/setup-chromedriver@42cc2998329f041de87dc3cfa33a930eacd57eaa

    - name: Run migrations
      run: flask db upgrade

    - name: Run seeder
      run: rosemary db:seed

    - name: Run system
      uses: JarvusInnovations/background-action@2428e7b970a846423095c79d43f759abf979a635
      with:
        run: flask run --host=0.0.0.0 --debug &
        wait-on: 'http://0.0.0.0:5000'
        
    - name: Run tests
      env:
        HEADLESS: true
      run: rosemary selenium
